---
- hosts: all
  become: True
  tasks:
    - include: tasks/deps.yml
    - name: get runit package
      get_url: 
          url: https://packagecloud.io/install/repositories/imeyer/runit/script.rpm.sh
          dest: /tmp/script.rpm.sh
    - name: add runit package to yum
      shell: bash /tmp/script.rpm.sh
      become: yes
    - name: install runit
      yum: name=runit-2.1.2-1.el6 state=present
    - name: install nginx
      yum: name=nginx-1.10.2-1.el6 state=present
    - name: Copy nginx.conf base configuration
      copy:
        src: config/nginx.conf
        dest: /etc/nginx/
    - name: Copy asapp server config files
      copy:
        src: config/asapp
        dest: /etc/nginx/asapp
    - name: Copy cert for ssl configuration
      copy:
        src: files/self-signed.crt
        dest: /etc/ssl/certs/asapp.crt
    - name: Create private key folder
      file:
        dest: /etc/ssl/private
        state: directory
    - name: Copy private key for ssl configuration
      copy:
        src: files/self-signed.key
        dest: /etc/ssl/private/asapp.key
    - name: Clean default configurations
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    - name: Copy application
      copy:
        src: application
        dest: /opt
    - name: Give run permissons to execute 
      file: dest=/opt/application/run mode=a+x
    - name: Runit run symbolic link 
      file:
        src: "/opt/application"
        dest: "/etc/service/application"
        state: link
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: Wait until runit detects and starts the application
      wait_for:
        path: /etc/service/application/supervise/pid